@BankingCoreApi_HostAddress = http://localhost:5255

GET {{BankingCoreApi_HostAddress}}/weatherforecast/
Accept: application/json

### Register
POST {{BankingCoreApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Test2 User2",
  "email": "test2@example.com",
  "phone": "+01234567890",
  "password": "Password123!"
}

### Login
POST {{BankingCoreApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "Password123!"
}
